[package]
name = "torrent-verify"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "torrent-verify"
path = "main.rs"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
anyhow = "1.0.104"
crypto = "0.5.1"
sha1 = "0.11.0"
generic-array = "1.4.5"
itertools = "0.15.0"
regex = "1.13.1"
log = "0.4.34"
rayon = "1.12.0"
unicode-normalization = "0.1.25"
base16ct = "1.0.0"
itoa = "1.0.18"
atoi = "3.1.0"
memmap2 = "0.9.11"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
